// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectHolOnBoardApi.Data;

#nullable disable

namespace ProjectHolOnBoardApi.Migrations
{
    [DbContext(typeof(ProjectHolOnBoardApiContext))]
    [Migration("20230314123142_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjectHolOnBoardApi.models.Anchor", b =>
                {
                    b.Property<int>("id_anchor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_anchor"), 1L, 1);

                    b.Property<string>("description_place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("id_string_anchor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("place_anchor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_anchor");

                    b.ToTable("Anchor");
                });

            modelBuilder.Entity("ProjectHolOnBoardApi.models.Circuit", b =>
                {
                    b.Property<int>("id_circuit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_circuit"), 1L, 1);

                    b.Property<string>("description_circuit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_circuit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_circuit");

                    b.ToTable("Circuit");
                });

            modelBuilder.Entity("ProjectHolOnBoardApi.models.Stage", b =>
                {
                    b.Property<int>("id_stage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_stage"), 1L, 1);

                    b.Property<int?>("Circuitid_circuit")
                        .HasColumnType("int");

                    b.Property<string>("description_stage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_Anchor")
                        .HasColumnType("int");

                    b.Property<int>("id_circuit")
                        .HasColumnType("int");

                    b.Property<string>("name_stage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_stage");

                    b.HasIndex("Circuitid_circuit");

                    b.HasIndex("id_Anchor");

                    b.ToTable("Stage");
                });

            modelBuilder.Entity("ProjectHolOnBoardApi.models.Stage", b =>
                {
                    b.HasOne("ProjectHolOnBoardApi.models.Circuit", "Circuit")
                        .WithMany("Stage")
                        .HasForeignKey("Circuitid_circuit");

                    b.HasOne("ProjectHolOnBoardApi.models.Anchor", "Anchor")
                        .WithMany()
                        .HasForeignKey("id_Anchor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anchor");

                    b.Navigation("Circuit");
                });

            modelBuilder.Entity("ProjectHolOnBoardApi.models.Circuit", b =>
                {
                    b.Navigation("Stage");
                });
#pragma warning restore 612, 618
        }
    }
}
